spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_db_stg
    username: anastasiia
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate # first time ddl-auto: update, after ddl-auto: validate
  sql:
    init:
      data-locations: classpath:data-stg.sql
      mode: never

logging:
  level:
    com.company.gym: INFO